name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore fable
      run: dotnet tool restore
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: install node modules
      run: npm install
    - name: run
      run: npm test

  build-and-test-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore fable
      run: dotnet tool restore
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: install node modules
      run: npm install
    - name: run
      run: npm test